# Generated by Django 2.1.2 on 2020-05-12 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_add_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vanue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.City')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='vanue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Vanue'),
        ),
    ]
